[package]
name = "egobox"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

[lib]
name = "ego"

[dependencies]
doe = { path="doe" }
gp = { path="gp" }
moe = { path="moe" }

ndarray = { version = "0.13.1", features = ["rayon", "approx", "blas"]}
ndarray-linalg = "0.12"
intel-mkl-src = { version = "0.5", default-features = false }
# # ndarray = { version = "0.14", features = ["rayon", "approx", "blas"]}
# # ndarray-linalg = { git = "https://github.com/rust-ndarray/ndarray-linalg.git" }
ndarray-stats = "0.3"
ndarray-rand = "0.11"
ndarray-npy = { version = "0.5", default-features = false }
linfa = { version="0.3.0", default-features = false }
nlopt = "0.5.3"
rand_isaac = "0.2"
libm = "0.2"
finitediff = { version="0.1", features = ["ndarray"] }

[dev-dependencies]
criterion = "0.3"
serde_json = "1"
approx = "0.3"
argmin_testfunctions = "0.1"


[workspace]

members = [
  "doe", 
  "pls",
  "gp",
  "moe"
]