[package]
name = "egobox"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

[lib]
name = "egobox"
crate-type = ["cdylib"]

[dependencies]
doe = { path="doe" }
gp = { path="gp" }
moe = { path="moe" }

linfa = { git="https://github.com/relf/linfa.git", features = ["intel-mkl-static"] }
linfa-pls = { git="https://github.com/relf/linfa.git", default-features = false }

ndarray = { version = "0.15", features = ["rayon", "approx", "blas"]}
ndarray-linalg = "0.14"
ndarray-stats = "0.5"
ndarray-rand = "0.14"
ndarray-npy = "0.8"
numpy = "0.14"

nlopt = "0.5.3"
rand_isaac = "0.3"
libm = "0.2"
finitediff = { version="0.1", features = ["ndarray"] }

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]

[dev-dependencies]
linfa-datasets = { git="https://github.com/relf/linfa.git", features = ["linnerud"] }
criterion = "0.3"
serde_json = "1"
approx = "0.4"
argmin_testfunctions = "0.1"

[workspace]
members = [
  "doe", 
  "gp",
  "moe"
]

[package.metadata.maturin]
python-source = "python"