[package]
name = "egobox"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [target.'cfg(windows)'.dependencies]
# ndarray = "0.13.1"

# [target.'cfg(unix)'.dependencies]
# ndarray = { version = "0.13.1", features = ["blas"] }
# blas-src = { version = "0.6.0", default-features = false, features = ["openblas"] }
# openblas-src = { version = "0.9.0", default-features = false, features = ["cblas"] }

[dependencies]
ndarray = { version = "0.13.1", features = ["rayon", "approx"]}
ndarray-linalg = "0.12"
ndarray-stats = "0.3"
ndarray_einsum_beta = "0.5"
ndarray-rand = "0.11"
ndarray-npy = { version = "0.5", default-features = false }
linfa = { version="0.2.1", default-features = false }
linfa-clustering = { version="0.2.1", default-features = false }
nlopt = "0.5"
rand_isaac = "0.2"
openblas-src = { version = "0.9", default-features = false, features = ["system"] }

[dev-dependencies]
criterion = "0.3"
serde_json = "1"
approx = "0.3"
