[package]
name = "egobox"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

[lib]
name = "ego"

[dependencies]
doe = { path="doe" }
gp = { path="gp" }
moe = { path="moe" }

linfa = { git="https://github.com/relf/linfa.git", features = ["intel-mkl-static"] }
ndarray = { version = "0.14", features = ["rayon", "approx", "blas"]}
ndarray-linalg = "0.13"
ndarray-stats = "0.4"
ndarray-rand = "0.13"
ndarray-npy = "0.7"

nlopt = "0.5.3"
rand_isaac = "0.3"
libm = "0.2"
finitediff = { version="0.1", features = ["ndarray"] }

[dev-dependencies]
linfa-datasets = { git="https://github.com/relf/linfa.git", features = ["linnerud"] }
criterion = "0.3"
serde_json = "1"
approx = "0.4"
argmin_testfunctions = "0.1"

[workspace]

members = [
  "doe", 
  "gp",
  "moe"
]