[package]
name = "gp"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

[lib]
name = "gp"

[dependencies]
doe = { path="../doe" }
pls = { path="../pls" }

linfa = { path="../../linfa", features = ["intel-mkl-static"] }
linfa-clustering = { path="../../linfa/algorithms/linfa-clustering", default-features = false }

ndarray = { version = "0.13.1", features = ["rayon", "approx"]}
ndarray-linalg = { version = "0.12.1" }
ndarray-stats = "0.3"
ndarray_einsum_beta = "0.5"
ndarray-rand = "0.11"
ndarray-npy = { version = "0.5", default-features = false }
nlopt = "0.5.3"
cobyla = "0.1.2"
rand_isaac = "0.2"

[dev-dependencies]
criterion = "0.3"
serde_json = "1"
approx = "0.3"

[[bench]]
name="gp"
harness = false

