[package]
name = "moe"
version = "0.1.0"
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"

[lib]
name="moe"

[dependencies]
doe = { path = "../doe" }
gp = { path = "../gp" }

linfa = { git="https://github.com/relf/linfa.git", features = ["intel-mkl-static"] }
linfa-clustering = { git="https://github.com/relf/linfa.git", default-features = false }
ndarray = { version = "0.13.1", features = ["rayon", "approx", "blas"]}
ndarray-linalg = "0.12"
ndarray-stats = "0.3"
ndarray-rand = "0.11"
rand_isaac = "0.2"

[dev-dependencies]
criterion = "0.3"
serde_json = "1"
approx = "0.3"
ndarray-npy = { version = "0.5", default-features = false }
ndarray-csv = "0.4"
csv = "1.1"